<?php

require_once(__DIR__.'/functions.php');
require_once(__DIR__.'/blocks.php');
require_once(__DIR__.'/coins.php');
require_once(__DIR__.'/rawcoins.php');
require_once(__DIR__.'/users.php');
require_once(__DIR__.'/payment.php');
require_once(__DIR__.'/stats.php');
require_once(__DIR__.'/system.php');
require_once(__DIR__.'/services.php');
require_once(__DIR__.'/sell.php');
require_once(__DIR__.'/clear.php');
require_once(__DIR__.'/renting.php');
require_once(__DIR__.'/markets.php');
require_once(__DIR__.'/notify.php');
require_once(__DIR__.'/bench.php');
require_once(__DIR__.'/mem.php');
require_once(__DIR__.'/stratdaem.php');
